/**
 * Drop Taste - Canonical design.md specification types
 * Schema version 1.0 generated by internal Drop Taste Managed Vision Service
 */

export interface DesignMdFrontmatter {
  schema_version: '1.0';
  pipeline: 'antigravity_vision_to_spec';
  source: {
    image_name: string;
    resolution: string; // e.g. "1920x1080"
    aspect_ratio: string; // e.g. "16:9"
    detected_type:
      | 'landing_page'
      | 'dashboard'
      | 'mobile_screen'
      | 'ui_component'
      | 'poster_graphic';
  };
  target: {
    framework: string; // e.g. "React (Next.js / Vite)"
    styling: string; // e.g. "Tailwind CSS v3.4+ / shadcn-compatible"
    token_format: string; // e.g. "CSS Custom Properties / Tailwind Config"
  };
}

export interface ExtractedColorToken {
  name: string;
  hex: string;
  role: 'canvas' | 'surface' | 'text_primary' | 'text_secondary' | 'accent' | 'border';
  contrastRatioAgainstCanvas?: string;
}

export interface ExtractedTypographyToken {
  level: string; // e.g. "Display / Hero", "Heading 1", "Body Regular"
  estimatedFontFamily: string; // e.g. "Plus Jakarta Sans, sans-serif"
  fontSizePx: number;
  fontWeight: number;
  lineHeightPx?: number;
  letterSpacing?: string;
}

export interface ExtractedSpacingToken {
  name: string;
  valuePx: number;
  usage: string;
}

export interface ComponentHierarchyNode {
  name: string;
  layout: 'Flexbox Row' | 'Flexbox Column' | 'Grid' | 'Absolute';
  alignment?: string;
  padding?: string;
  gap?: string;
  children?: ComponentHierarchyNode[];
  notes?: string;
}

export interface ParsedDesignMd {
  frontmatter: DesignMdFrontmatter;
  context: {
    primaryPurpose: string;
    targetAudience: string;
    visualTone: string;
  };
  tokens: {
    colors: ExtractedColorToken[];
    typography: ExtractedTypographyToken[];
    spacing: ExtractedSpacingToken[];
  };
  hierarchy: ComponentHierarchyNode[];
  visualTraits: string[];
  codeTemplate?: string;
  rawMarkdown: string;
}
